name: torch_env
channels:
  - pytorch
  - http://conda.anaconda.org/gurobi
  - defaults
  - conda-forge
  - bioconda
dependencies:
  - bwa=0.7.17=hed695b0_6
  - boost=1.68.0=py36h8619c78_1001
  - boost-cpp=1.68.0=h11c811c_1000
  - bzip2=1.0.8=h516909a_1
  - ca-certificates=2019.11.28=hecc5488_0
  - cairo=1.16.0=h18b612c_1001
  - certifi=2019.11.28=py36_0
  - cloudpickle=1.2.2=py_1
  - cytoolz=0.10.1=py36h516909a_0
  - dask-core=2.9.0=py_0
  - dbus=1.13.6=he372182_0
  - fontconfig=2.13.1=he4413a7_1000
  - gettext=0.19.8.1=hc5be6a0_1002
  - glib=2.58.3=h6f030ca_1002
  - gst-plugins-base=1.14.5=h0935bb2_0
  - gstreamer=1.14.5=h36ae1b5_0
  - imageio=2.6.1=py36_0
  - jpeg=9c=h14c3975_1001
  - libiconv=1.15=h516909a_1005
  - libuuid=2.32.1=h14c3975_1000
  - matplotlib-base=3.1.1=py36hfd891ef_0
  - networkx=2.4=py_0
  - openssl=1.1.1d=h516909a_0
  - pixman=0.38.0=h516909a_1003
  - pycairo=1.18.1=py36h438ddbb_0
  - pywavelets=1.1.1=py36hc1659b7_0
  - qt=5.9.7=h52cfd70_2
  - rdkit=2019.03.2=py36h9c20d5c_0
  - scikit-image=0.16.2=py36hb3f55d8_0
  - tk=8.6.10=hed695b0_0
  - toolz=0.10.0=py_0
  - xorg-kbproto=1.0.7=h14c3975_1002
  - xorg-libice=1.0.10=h516909a_0
  - xorg-libsm=1.2.3=h84519dc_1000
  - xorg-libx11=1.6.8=h516909a_0
  - xorg-libxext=1.3.4=h516909a_0
  - xorg-libxrender=0.9.10=h516909a_1002
  - xorg-renderproto=0.11.1=h14c3975_1002
  - xorg-xextproto=7.3.0=h14c3975_1002
  - xorg-xproto=7.0.31=h14c3975_1007
  - _libgcc_mutex=0.1=main
  - absl-py=0.8.1=py36_0
  - backcall=0.1.0=py36_0
  - biopython=1.74=py36h7b6447c_0
  - blas=1.0=mkl
  - c-ares=1.15.0=h7b6447c_1001
  - cffi=1.12.3=py36h2e261b9_0
  - cudatoolkit=10.0.130=0
  - cycler=0.10.0=py36_0
  - decorator=4.4.0=py36_1
  - expat=2.2.6=he6710b0_0
  - freetype=2.9.1=h8a8886c_1
  - grpcio=1.16.1=py36hf8bcb03_1
  - icu=58.2=h9c2bf20_1
  - intel-openmp=2019.4=243
  - ipykernel=5.1.2=py36h39e3cac_0
  - ipython=7.8.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - jedi=0.15.1=py36_0
  - joblib=0.13.2=py36_0
  - jupyter_client=5.3.1=py_0
  - jupyter_core=4.5.0=py_0
  - kiwisolver=1.1.0=py36he6710b0_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.9.2=hd408876_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.0.10=h2733197_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=hea5a465_1
  - markdown=3.1.1=py36_0
  - matplotlib=3.1.1=py36h5429711_0
  - mkl=2019.4=243
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.0=py36hd6b4f25_0
  - ncurses=6.1=he6710b0_1
  - ninja=1.9.0=py36hfd86e86_0
  - numpy=1.17.3=py36hd14ec0e_0
  - numpy-base=1.17.3=py36hde5b4d6_0
  - olefile=0.46=py36_0
  - pandas=0.25.1=py36he6710b0_0
  - parso=0.5.1=py_0
  - patsy=0.5.1=py36_0
  - pcre=8.43=he6710b0_0
  - perl=5.26.2=h14c3975_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pillow=6.1.0=py36h34e0f95_0
  - pip=19.2.2=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - protobuf=3.9.2=py36he6710b0_0
  - ptyprocess=0.6.0=py36_0
  - pycparser=2.19=py36_0
  - pygments=2.4.2=py_0
  - pyparsing=2.4.2=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - python=3.6.9=h265db76_0
  - python-dateutil=2.8.0=py36_0
  - pytz=2019.2=py_0
  - pyzmq=18.1.0=py36he6710b0_0
  - readline=7.0=h7b6447c_5
  - scikit-learn=0.21.3=py36hd81dba3_0
  - scipy=1.3.1=py36h7c811a0_0
  - seaborn=0.9.0=py36_0
  - setuptools=41.0.1=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.29.0=h7b6447c_0
  - statsmodels=0.10.1=py36hdd07704_0
  - tbb=2019.8=hfd86e86_0
  - tbb4py=2019.8=py36hfd86e86_0
  - tensorboard=1.14.0=py36hf484d3e_0
  - tornado=6.0.3=py36h7b6447c_0
  - traitlets=4.3.2=py36_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - werkzeug=0.16.0=py_0
  - wheel=0.33.4=py36_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytorch=1.2.0=py3.6_cuda10.0.130_cudnn7.6.2_0
  - torchvision=0.4.0=py36_cu100
  - pip:
    - chardet==3.0.4
    - dask==2.9.0
    - idna==2.8
    - jsonpatch==1.24
    - jsonpointer==2.0
    - lxml==4.4.1
    - modlamp==4.1.1
    - nose==1.3.7
    - opencv-python==4.2.0.34
    - requests==2.22.0
    - scikit-multilearn==0.2.0
    - torch==1.2.0
    - torchfile==0.1.0
    - urllib3==1.25.3
    - visdom==0.1.8.9
    - websocket-client==0.56.0
prefix: /data/user_home/gbkim/anaconda3/envs/torch_env

